/*             Data Structure Mini Project
AUTHOR : heenaansari
github : heenaansari
			 * 		    TOPIC:: Patient Management System.
			 *                                 	
														
						 
			 * Summary: 
			 * 1. Our project topic is "Patient Management System" which is designed aiming to manage the patient records in common hospitals.
			 * 2. This system is designed to register, search, delete and display all the patient records.
			 * 3. Each patient has got an autogenerated Patient ID.
			 * 4. In the given program, we use modular approach to manage our patient record using linked lists.
			 * 5. The following are the user defined functions used here: registration()-to register the new patient record, search()-to search and display  
			 *    the given patient record, delete()-to delete the given record.
			 * 6. The advantages of this system is that it helps to reduce the paperwork for managing the patient record as well as provides easy
			      accessibility to any record.
			 * 7. The interface is designed to be user friendly.
			 * 8. When hospital's use this system they can save the details of the patient's more securely than it is done manually.
			 * 9. This program also provides inbuilt user ID and password.
			 *	  Misplacing and mishandeling is impossible with this system than the manual procedure.
			 *             So wecan recommend this system as trustworthy and securable one as information can be accessed by authorized user.  
			 * */
			#include<stdio.h>
			#include<stdlib.h>
			#include<unistd.h>
			#include<string.h>
			int idl=0;
			int MAX=30;
			struct patient	//Global structure of patient
			{
				int agep,weightp,idp;
				char pnamep[20],namep[20],lastnamep[20],genp[2],bgp[5],ptypep[10],pastp[10],famp[10],medp[100],datep[30],timep[30],algp[10],addressp[30],datedisp[50],billp[50];
				char contactp[10];
				struct patient *next;
			};



			struct patient *registration(struct patient *h,int  id,char name[],char lastname[],int age,char gen[],int weight,char contact[],char address[],char date[],char time[],char ptype[],char bg[],char alg[],char past[],char fam[],char med[])
			{//Function to register new patient record
				
							struct patient *p,*tmp;
							p=(struct patient *)malloc(sizeof(struct patient));    //allocating memory to the new node
							if(p==NULL)
							{
								printf("\n Not enough memory to allocate.");
							   
							}
							else
							
							{p->idp=id;
							strcpy(p->namep,name);
							strcpy(p->lastnamep,lastname);
							p->agep=age;
							strcpy(p->genp,gen);
							p->weightp=weight;
							strcpy(p->contactp,contact);
							strcpy(p->addressp,address);
							strcpy(p->datep,date);
							strcpy(p->timep,time);
							strcpy(p->ptypep,ptype);
							strcpy(p->bgp,bg);
							strcpy(p->algp,alg);
							strcpy(p->pastp,past);
							strcpy(p->famp,fam);
							strcpy(p->medp,med);
							
							p->next=NULL;
							if(h==NULL)
							{h=p;
							}
							else
							{
								tmp=h;
								while(tmp->next!=NULL)   
							   { tmp=tmp->next;
							   }
							   tmp->next=p;
						   }
					   }
							   
							return h;
			}

			struct patient *removegiven(struct patient *h,int key)
			{ //function to delete given patient record
			   
				
				
				struct patient *temp,*prev;
				temp=prev=h;
				if(h==NULL)
				printf("No  record present(Empty)");
				else
				{
					while(temp!=NULL&&temp->idp!=key)
					{
						
						prev=temp;
						temp=temp->next;
					}
			if(temp!=NULL&&temp==h)
			{
				h=temp->next;
				temp=NULL;
				free(temp);
			}
			if(temp!=NULL)
			{
				
				prev->next=temp->next;
				temp->next=NULL;
				free(temp);
				printf("\n\t***DELETED RECORD SUCCESSFULLY***");
			}
			else
			{
				printf("Record not found");
			}
			}
			return h;
			}

			struct patient *updaterecord(struct patient *h,int id,char update[])
			{//Function to update cureent medical details of the given record
				struct patient *temp,*prev;
				temp=prev=h;
				if(h==NULL)
				printf("\nEmpty Record");
				else
				{
					while(temp!=NULL&&temp->idp!=id)
					{
						prev=temp;
						temp=temp->next;
					}
					if(temp!=NULL)
					{
						strcat(temp->medp,update );
					}
					else
					{
						printf("\nRecord not found");
						}
				}
				
				return h;
				}
				
				 
				  struct patient *updatedischarge(struct patient *h,int id,char datedis[],char bill[])
			{
				//Function to update discharge details
				struct patient *temp,*prev;
				temp=prev=h;
				if(h==NULL)
				printf("\nEmpty Record");
				else
				{
					while(temp!=NULL&&temp->idp!=id)
					{
						prev=temp;
						temp=temp->next;
					}
					if(temp!=NULL)
					{
						strcpy(temp->datedisp,datedis);
						strcpy(temp->billp,bill);
					}
					else
					{
						printf("\nRecord not found");
					}
				}
				
				return h;
				}
				
				 
			struct patient *search(struct patient *h,int id)
			{
				//Function to search and display given record
				struct patient *temp,*prev;
				temp=prev=h;
				if(h==NULL)
				printf("No  record present(Empty)");
				else
				{
					while(temp!=NULL&&temp->idp!=id)
					{
						prev=temp;
						temp=temp->next;
					}

			if(temp!=NULL)
			{
				printf("Record Found!\nDetails of id= %d are as follows::",id);
				 printf("\nId:: %d\nName:: %s %s\n\tAge:: %d\n\tGender:: %s\n\tContact Number::%s\n\tAdress::%s\n\tWeight:: %d\n\tDate:: %s\n\tTime:: %s",temp->idp,temp->namep,temp->lastnamep,temp->agep,temp->genp,temp->contactp,temp->addressp,temp->weightp,temp->datep,temp->timep);
			   printf("\n\tType:: %s\n\tBlood group:: %s\n\tAllgeries:: %s\n\tPast record:: %s\n\tFamily record:: %s\n\tMedical Current Status:: %s",temp->ptypep,temp->bgp,temp->algp,temp->pastp,temp->famp,temp->medp);
			}
			else
			{
				printf("\nRecord not found");
			}
			}
			return h;
			}


			void displaydis(struct patient *h,int id)
			{
				struct patient *temp;
				temp=h;
				if(h==NULL)
				printf("\nNo Records Found");
				
				else
				{
					while(temp!=NULL&&temp->idp!=id)
					{
						
						temp=temp->next;
					}
					if(temp!=NULL)
					{
					//	printf("\nDischarge Details of id = %d",temp->idp);
						//printf("\nAdmit date is %s");
						printf("\nDischarge details of Id= %d is::\n\t Name::%s %s\n\tAdmit Date:: %s\n\tDischarge Date:: %s\n \t Bill Amount:: %s\n",temp->idp,temp->namep,temp->lastnamep,temp->datep,temp->datedisp,temp->billp);
					}
					else
			{
				printf("\nRecord not found");
			}
			}
				
				
			}


			 void display(struct patient *h)  //TO DISPLAY THE LINKED LIST
						{
							//Function to display all recorsds
							struct patient *temp;
							if(h==NULL)
								printf("\nNO record found");
								else
								{
									temp=h;
						   
								printf("\n\n\tRecord::");
								while(temp!=NULL)
								{
									printf("\nId:: %d\nName:: %s %s\n\tAge:: %d\n\tGender:: %s\n\tContact Details::%s\n\tAddress::%s\n\tWeight:: %d\n\tDate:: %s\n\tTime:: %s",temp->idp,temp->namep,temp->lastnamep,temp->agep,temp->genp,temp->contactp,temp->addressp,temp->weightp,temp->datep,temp->timep);
									printf("\n\tType:: %s\n\tBlood Group:: %s\n\tAllgeries:: %s\n\tPast record:: %s\n\tFamily record:: %s\n\tMedical Current Status:: %s",temp->ptypep,temp->bgp,temp->algp,temp->pastp,temp->famp,temp->medp);
									temp=temp->next;
								}
							}
							
						   
			}


			int main()
			{

				
				struct patient *head;
				
				head=NULL;
				
			int ch,id,age,weight,i,j;
			char name[20],lastname[20],gen[2],bg[5],ptype[10],alg[MAX],past[MAX],fam[MAX],med[MAX],date[30],time[30],num[10],address[MAX],update[50],datedis[50],bill[50];
			char user[]="a",password[]="a",iuser[2],ipassword[2];
			printf("\n\t\t\t\t\t\t******WELCOME TO PATIENT MANAGEMENT SYSTEM******");
			printf("\n\t\t\t\tUSER ID ::"); //checking user id and password
			scanf("%s",iuser);
			printf("\n\t\t\t\tPASSWORD ::");
			scanf("%s",ipassword);
			i=strcmp(user,iuser);
			j=strcmp(password,ipassword);
			if(i==0&&j==0)
			{
			while(1)
			{
			printf("\n\t\t\t MENU  \n \t 1. Registration.\n \t 2. Search Patient.\n \t 3. Update Record. \n \t 4. Delete Record.\n \t 5. Display Records.\n \t 6. Update Discharge Details.\n \t 7. Display discharge details \n \t 8. Exit. \n \t");
			printf("\t ENTER YOUR CHOICE :: ");
			scanf("%d",&ch);
			switch(ch)
			{

			case 1:

			idl=idl+1;

			printf("\n\tPLEASE ENTER THE FOLLOWING DETAILS :\n\n\t***PERSONAL DETAILS***\n");

			printf("\n ID::%d \n\t1.NAME(full_name):",idl);
			scanf("%s",name);
			scanf("%s",lastname);

			printf("\n\t2.AGE:");
			scanf("%d",&age);

			printf("\n\t3.GENDER(M/F):");
			scanf("%s",gen);

			printf("\n\t4.WEIGHT:");
			scanf("%d",&weight);

			printf("\n\t5.DATE(DD/MM/YYYY):");
			scanf("%s",date);

			printf("\n\t6.TIME(hh:mm):");
			scanf("%s",time);
			printf("\n\t7.TYPE OF PATIENT: *EMERGENCY.   *CONSULTANCY.   *REGULAR/OPD. :: ");
			scanf("%s",ptype);

			printf("\n\t\t\t***MEDICAL DETAILS***");
			printf("\n\t1.BLOOD GROUP(p-Positive/n-Negative):");
			scanf("%s",bg);
			printf("\n\t2.ALLERGIES:");
			scanf("%s",alg);
			printf("\n\t3.PAST HISTORY:");
			scanf("%s",past);
			printf("\n\t4.FAMILY HISTORY:");
			scanf("%s",fam);
			printf("\n\t5.CURRENT MEDICATION STATUS:");
			scanf("%s",med);

			printf("\n\t ***CONTACT DETAILS***");
			printf("\n\t Contact Number::");
			scanf("%s",num);
			printf("\n\tAddress::");
			scanf("%s",address);
			 head=registration(head,idl,name,lastname,age,gen,weight,num,address,date,time,ptype,bg,alg,past,fam,med);
			 printf("\n\t !!! REGISTRATION DONE SUCCESSFULLY !!! ");
			break;
			case 2:
			printf("\n  Enter patient details ::\n\t UNIQUE ID ::");
			scanf("%d",&id);


			head=search(head,id);

			break;
			case 3:
			printf("Enter id::");
			scanf("%d",&id);
			printf("\n**NOTE::Precede your updates with '*'");
			printf("\nEnter the  medical details to be updated::");
			scanf("%s",update);
			head=updaterecord(head,id,update);

			break;

			case 4:
			printf("Enter the unique id ::");
			scanf("%d",&id);

			head=removegiven(head,id);
			break;

			case 5:
			display(head);
			break;
			case 6:
			printf("\nEnter id::");
			scanf("%d",&id);
			printf("\nEnter discharge Date::");
			scanf("%s",datedis);
			printf("\nEnter Bill amount::");
			scanf("%s",bill);

			head=updatedischarge(head,id,datedis,bill);
			break;
			case 7:
			printf("\nEnter id::");
			scanf("%d",&id);
			displaydis(head,id);

			break;
			case 8:
			printf("\n \t *******THANK YOU*******");
			exit(0);
			break;
			default:
			printf("\n\t Sorry !!! Please enter the correct option. Thank you!!!");
			}
			}
			}
			else
			{
				printf("Access Denied. \tIncorrect User id or Password");
			}

			return 0;
			}




			/*OUTPUT
			 
									******WELCOME TO PATIENT MANAGEMENT SYSTEM******
							USER ID ::a

							PASSWORD ::a

						 MENU  
				 1. Registration.
				 2. Search Patient.
				 3. Update Record. 
				 4. Delete Record.
				 5. Display Records.
				 6. Update Discharge Details.
				 7. Display discharge details 
				 8. Exit. 
					 ENTER YOUR CHOICE :: 1

				PLEASE ENTER THE FOLLOWING DETAILS :

				***PERSONAL DETAILS***

			 ID::1 
				1.NAME(full_name):NEHA PAL

				2.AGE:17

				3.GENDER(M/F):F

				4.WEIGHT:58

				5.DATE(DD/MM/YYYY):19/10/2018

				6.TIME(hh:mm):04:00

				7.TYPE OF PATIENT: *EMERGENCY.   *CONSULTANCY.   *REGULAR/OPD. :: OPD

						***MEDICAL DETAILS***
				1.BLOOD GROUP(p-Positive/n-Negative):Op

				2.ALLERGIES:DUST

				3.PAST HISTORY:BP

				4.FAMILY HISTORY:NONE

				5.CURRENT MEDICATION STATUS:DIABETES

				 ***CONTACT DETAILS***
				 Contact Number::9980981256

				Address::PANVEL,NaviMumbai

				 !!! REGISTRATION DONE SUCCESSFULLY !!! 
						 MENU  
				 1. Registration.
				 2. Search Patient.
				 3. Update Record. 
				 4. Delete Record.
				 5. Display Records.
				 6. Update Discharge Details.
				 7. Display discharge details 
				 8. Exit. 
					 ENTER YOUR CHOICE :: 3
			Enter id::1

			**NOTE::Precede your updates with '*'
			sEnter the  medical details to be updated::*MALARIA

						 MENU  
				 1. Registration.
				 2. Search Patient.
				 3. Update Record. 
				 4. Delete Record.
				 5. Display Records.
				 6. Update Discharge Details.
				 7. Display discharge details 
				 8. Exit. 
					 ENTER YOUR CHOICE :: 5


				Record::
			Id:: 1
			Name::NEHA PAL
				Age:: 17
				Gender:: F
				Contact Details::9980981256
				Address::PANVEL,NaviMumbai
				Weight:: 58
				Date:: 19/10/2018
				Time:: 04:00
				Type:: OPD
				Blood Group:: Op
				Allgeries:: DUST
				Past record:: BP
				Family record:: NONE
				Medical Current Status:: DIABETES*MALARIA
						 MENU  
				 1. Registration.
				 2. Search Patient.
				 3. Update Record. 
				 4. Delete Record.
				 5. Display Records.
				 6. Update Discharge Details.
				 7. Display discharge details 
				 8. Exit. 
					 ENTER YOUR CHOICE :: 6

			Enter id::1

			Enter discharge Date::20/10/2018

			Enter Bill amount::9000

						 MENU  
				 1. Registration.
				 2. Search Patient.
				 3. Update Record. 
				 4. Delete Record.
				 5. Display Records.
				 6. Update Discharge Details.
				 7. Display discharge details 
				 8. Exit. 
					 ENTER YOUR CHOICE :: 7

			Enter id::1

			Discharge details of Id= 1 is::
				Name::NEHA PAL
				Admit Date:: 19/10/2018
				Discharge Date:: 20/10/2018
				Bill Amount:: 9000

						 MENU  
				 1. Registration.
				 2. Search Patient.
				 3. Update Record. 
				 4. Delete Record.
				 5. Display Records.
				 6. Update Discharge Details.
				 7. Display discharge details 
				 8. Exit. 
					 ENTER YOUR CHOICE :: 2

			  Enter patient details ::
				 UNIQUE ID ::1
			Record Found!
			Details of id= 1 are as follows::
			Id:: 1
			Name::NEHA PAL
				Age:: 17
				Gender:: F
				Contact Number::9980981256
				Adress::PANVEL,NaviMumbai
				Weight:: 58
				Date:: 19/10/2018
				Time:: 04:00
				Type:: OPD
				Blood group:: Op
				Allgeries:: DUST
				Past record:: BP
				Family record:: NONE
				Medical Current Status:: DIABETES*MALARIA
						 MENU  
				 1. Registration.
				 2. Search Patient.
				 3. Update Record. 
				 4. Delete Record.
				 5. Display Records.
				 6. Update Discharge Details.
				 7. Display discharge details 
				 8. Exit. 
				 
					 ENTER YOUR CHOICE :: 4
			Enter the unique id ::1
			***DELETED RECORD SUCCESSFULLY***
						 MENU  
				 1. Registration.
				 2. Search Patient.
				 3. Update Record. 
				 4. Delete Record.
				 5. Display Records.
				 6. Update Discharge Details.
				 7. Display discharge details 
				 8. Exit. 
				 
					 ENTER YOUR CHOICE :: 8

				 *******THANK YOU*******

			*/
			/**
			 * CONCLUSION::
			 * 			We have successfully implemented the patient record management system using linked list.
			 * */

